TestTaskLibrary/Models/Books/AddBookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TestTaskLibrary.Models.Books
{
    public class AddBookViewModel
    {
        [Required(ErrorMessage = "Поле Автор является обязательным")]
        [Display(Name = "Автор")]
        public string Author { get; set; }

        [Required(ErrorMessage = "Поле Название является обязательным")]
        [Display(Name = "Название")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Поле Жанр является обязательным")]
        [Display(Name = "Жанр")]
        public string Genre { get; set; }
    }
}

TestTaskLibrary/Models/Books/BookListItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestTaskLibrary.Models.Books
{
    public class BookListItemViewModel
    {
        
        public int Id { get; set; }

        public string Author { get; set; }

        public string Title { get; set; }

        public string Genre { get; set; }

        public string Status { get; set; }
    }
}

TestTaskLibrary/Models/Books/BooksMapping.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.Commands;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.ViewModels;

namespace TestTaskLibrary.Models.Books
{
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            CreateMap<AddBookViewModel, CreateBookCommand > ().ReverseMap();
        }
    }
}

TestTaskLibrary/Models/Books/IssueViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TestTaskLibrary.Domain.Core;

namespace TestTaskLibrary.Models.Books
{
    public class IssueViewModel
    {
        [Required]
        [HiddenInput]
        public int BookId { get; set; }

        [Display(Name = "Email клиента")]
        [Required(ErrorMessage = "Поле Email является обязательным")]
        public string UserEmail { get; set; }
    }
}

TestTaskLibrary/Models/Library/BookDatailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestTaskLibrary.Models.Library
{
    public class BookDatailsViewModel
    {
        public int Id { get; set; }

        public string Author { get; set; }

        public string Title { get; set; }

        public string Genre { get; set; }
    }
}

TestTaskLibrary/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.Commands;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.Queries;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.ViewModels;
using TestTaskLibrary.Domain.Application.Interfaces.Managers;
using TestTaskLibrary.Domain.Application.Interfaces.Repositories;
using TestTaskLibrary.Domain.Core;
using TestTaskLibrary.Infrastructure.Business;
using TestTaskLibrary.Infrastructure.Data;
using TestTaskLibrary.Models;
using TestTaskLibrary.Models.Books;

namespace TestTaskLibrary.Controllers
{
    [Authorize(Roles = RoleTypes.Librarian)]
    public class BooksController : GenericController<Book,BookViewModel>
    {

        public BooksController(IMediator mediator, IGenericRepository<Book> repository, IMapper mapper) : base(repository, mediator, mapper)
        {
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        //public async Task<IActionResult> List()
        //{
        //    var result = await mediator.Send(new GetBooksQuery());
        //    return View(result);
        //}

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> BookDatails(GetBookByIdQuery query)
        {
            var book = await mediator.Send(query);

            if (book != null)
            {
                return View(book);
            }

            return NotFound();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new AddBookViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                var command = mapper.Map<CreateBookCommand>(model);
                int id = await mediator.Send(command);
                return RedirectToAction("List");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteBookCommand command)
        {
            int id = await mediator.Send(command);
            return RedirectToAction("List");
        }
    }
}

TestTaskLibrary/Controllers/LibraryController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Threading.Tasks;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.Queries;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.ViewModels;
using TestTaskLibrary.Domain.Application.Features.Library.Commands;
using TestTaskLibrary.Domain.Application.Interfaces.Repositories;
using TestTaskLibrary.Domain.Core;
using TestTaskLibrary.Models;

namespace TestTaskLibrary.Controllers
{
    [Authorize]
    public class LibraryController : GenericController<Book, BookViewModel>
    {
        private readonly UserManager<User> userManager;

        public LibraryController(IGenericRepository<Book> repository, IMediator mediator, IMapper mapper, UserManager<User> userManager) : base(repository, mediator, mapper)
        {
            this.userManager = userManager;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            if (User.IsInRole(RoleTypes.Admin))
            {
                return RedirectToAction("List", "Users");
            }
            if (User.IsInRole(RoleTypes.Librarian))
            {
                return RedirectToAction("List", "Books");
            }
            return RedirectToAction("List");
        }

        [AllowAnonymous]
        public override async Task<IActionResult> List(int? pageIndex, int? pageSize, string search, string searchField, string sortField)
        {
            //var books = await mediator.Send(getBooksQuery);

            //if (search != null)
            //{
            //    switch (fieldSearch)
            //    {
            //        case FieldSearchType.Author:
            //            books = books.Where(b => b.Author?.ToLower().Contains(search.ToLower()) ?? false).ToList();
            //            break;
            //        case FieldSearchType.Title:
            //            books = books.Where(b => b.Title?.ToLower().Contains(search.ToLower()) ?? false).ToList();
            //            break;
            //        case FieldSearchType.Genre:
            //            books = books.Where(b => b.Genre?.ToLower().Contains(search.ToLower()) ?? false).ToList();
            //            break;
            //        default:
            //            books = books.Where(b => b.Title?.ToLower().Contains(search.ToLower()) ?? false).ToList();
            //            break;
            //    }
            //}
            //var bookViewModel = new LibraryListViewModel()
            //{
            //    Search = getBooksQuery.Search,
            //    SearchType = getBooksQuery.SearchType ?? FieldSearchType.Title,
            //    Books = books,
            //    PageIndex = getBooksQuery.PageIndex
            //};
            ViewData["User"] = await userManager.GetUserAsync(User);

            return await base.List(pageIndex, pageSize, search, searchField, sortField);
        }

        [HttpPost]
        public async Task<IActionResult> Book(BookCommand command, int? pageIndex, int? pageSize, string search, string searchField, string sortField)
        {
            await mediator.Send(command);
            return RedirectToAction("List", new { pageIndex, pageSize, search, searchField, sortField });
        }

        [HttpPost]
        public async Task<IActionResult> Unbook(UnbookCommand command, int? pageIndex, int? pageSize, string search, string searchField, string sortField)
        {
            await mediator.Send(command);
            return RedirectToAction("List", new { pageIndex, pageSize, search, searchField, sortField });
        }

        [HttpGet]
        public async Task<IActionResult> Issue(GetBookByIdQuery query)
        {
            if (ModelState.IsValid)
            {
                var book = await mediator.Send(query);
                if (book != null)
                {
                    return View(new IssueBookCommand() { BookId = book.Id, UserEmail = book.CurrentStatus.User?.UserName });
                }
            }
            return RedirectToAction("List", "Books");
        }

        [HttpPost]
        [Authorize(Roles = RoleTypes.Librarian)]
        public async Task<IActionResult> Issue(IssueBookCommand command)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByNameAsync(command.UserEmail);
                if (user != null)
                {
                    if (await mediator.Send(command))
                    {
                        return RedirectToAction("List", "Books");
                    }
                }
                else
                {
                    ModelState.AddModelError("UserEmail", "Пользователь с таким Email не найден");
                }
            }
            return View(command);
        }

        [HttpPost]
        [Authorize(Roles = RoleTypes.Librarian)]
        public async Task<IActionResult> Take(TakeBookCommand command, int? pageIndex, int? pageSize, string search, string searchField, string sortField)
        {
            await mediator.Send(command);
            return RedirectToAction("List", "Books", new { pageIndex, pageSize, search, searchField, sortField });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestTaskLibrary/Controllers/OData/BooksController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using MediatR;
using Microsoft.AspNet.OData;
using Microsoft.AspNet.OData.Routing;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.Commands;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.ViewModels;
using TestTaskLibrary.Domain.Application.Features.Library.Commands;
using TestTaskLibrary.Domain.Application.Interfaces.Repositories;
using TestTaskLibrary.Domain.Core;
using TestTaskLibrary.Models;
using TestTaskLibrary.Models.Books;

namespace TestTaskLibrary.Controllers.OData
{

    public class BooksController : GenericController<Book, BookViewModel>
    {
        private readonly UserManager<User> userManager;

        public BooksController(IMediator mediator, IGenericRepository<Book> repository, IMapper mapper, UserManager<User> userManager) : base(mediator, repository, mapper)
        {
            this.userManager = userManager;
        }

        [AllowAnonymous]
        public override IActionResult Get()
        {
            return base.Get();
        }

        [AllowAnonymous]
        public IActionResult Get(int key)
        {
            return Ok(repository.GetAll().ProjectTo<BookViewModel>(mapper.ConfigurationProvider).FirstOrDefault(i => i.Id == key));
        }

        [EnableQuery]
        [AllowAnonymous]
        public IQueryable<ReviewViewModel> GetReviews([FromODataUri]int key)
        {
            return repository.GetAll().Where(b => b.Id == key).SelectMany(b => b.BookAdditionalInfo.Reviews).ProjectTo<ReviewViewModel>(mapper.ConfigurationProvider);
        }

        [AllowAnonymous]
        [EnableQuery]
        [ODataRoute("Books({key})/Reviews({id})")]
        public SingleResult<ReviewViewModel> GetReviews(int key, int id)
        {
            var result = repository.GetAll().Where(b => b.Id == key).SelectMany(b => b.BookAdditionalInfo.Reviews).Where(r => r.Id == id).ProjectTo<ReviewViewModel>(mapper.ConfigurationProvider);
            return SingleResult.Create(result);
        }

        public async Task<IActionResult> Post([FromBody]AddBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                var command = mapper.Map<CreateBookCommand>(model);
                int id = await mediator.Send(command);
                return Ok(id);
            }
            return BadRequest(ModelState);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = "Basic", Roles = RoleTypes.Customer)]
        public async Task<IActionResult> Book(int key)
        {
            var result = await mediator.Send(new BookCommand() { Id = key });
            if (result)
            {
                return Ok();
            }
            return BadRequest();
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = "Basic", Roles = RoleTypes.Customer)]
        public async Task<IActionResult> Unbook(int key)
        {
            var result = await mediator.Send(new UnbookCommand() { BookId = key });
            if (result)
            {
                return Ok();
            }
            return BadRequest();
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = "Basic", Roles = RoleTypes.Librarian)]
        public async Task<IActionResult> Issue([FromODataUri]int key, ODataActionParameters parameters)
        {
            var user = await userManager.FindByNameAsync((string)parameters["UserEmail"]);
            if (user != null)
            {
                if (await mediator.Send(new IssueBookCommand() { BookId = key, UserEmail = (string)parameters["UserEmail"] }))
                {
                    return Ok();
                }
            }
            else
            {
                ModelState.AddModelError("UserEmail", "Пользователь с таким Email не найден");
                return NotFound(ModelState);
            }
            return BadRequest();
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = "Basic", Roles = RoleTypes.Librarian)]
        public async Task<IActionResult> Take(int key)
        {
            var result = await mediator.Send(new TakeBookCommand() { BookId = key });
            if (result)
            {
                return Ok();
            }
            return BadRequest();
        }
    }
}

TestTaskLibrary/Views/Books/Add.cshtml
@model TestTaskLibrary.Models.Books.AddBookViewModel

@{
    ViewData["Title"] = "Add";
}
<h3 class="mb-2">Добавить книгу</h3>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List" asp-controller="Books">Вернуться</a>
</div>

TestTaskLibrary/Views/Books/BookDatails.cshtml
@model BookViewModel
@{
    ViewData["Title"] = "BookDatails";
}
<div class="mt-1">
    <div class="d-flex justify-content-between">
        <img src="~/Books/images/@Model.ImageName" />
        <div class="d-flex flex-column">
            <h2>@Model.Title</h2>
            <div class="align-self-end">
                <div>
                    <span>@await Component.InvokeAsync(nameof(AverageRating), new { bookId = Model.Id })</span>
                </div>
                <div>
                    <span>@Model.Author</span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="mt-2">
    <h4>Отзывы</h4>
    <div class="row">
        <div class="col-4">
            @if (User.Identity.IsAuthenticated)
            {
                @await Component.InvokeAsync(nameof(UsersReview), new { id = Model.Id })
            }
            @await Component.InvokeAsync(nameof(BookComments), new { id = Model.Id })
        </div>
    </div>
</div>

TestTaskLibrary/Views/Books/Issue.cshtml
@model TestTaskLibrary.Models.Books.IssueViewModel

@{
    ViewData["Title"] = "Issue";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Issue" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BookId" class="form-control" />
            <div class="form-group">
                <label asp-for="UserEmail" class="control-label"></label>
                <input asp-for="UserEmail" class="form-control" />
                <span asp-validation-for="UserEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Выдать книгу" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Вернуться</a>
</div>

TestTaskLibrary/Views/Books/ItemButtons.cshtml
<div class="btn-group">
    @if ((Status)ViewData["Status"] != Status.Issued)
    {
        <a asp-action="Issue" asp-controller="Library" asp-route-id="@ViewData["id"]" class="btn btn-outline-primary">Выдать</a>
    }
    else
    {
        <form class="input-group-prepend" asp-action="Take" asp-controller="Library" method="post">
            <input type="hidden" name="BookId" value="@ViewData["id"]" />
            <input class="btn btn-primary" type="submit" value="Вернуть" />
        </form>
    }
    <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" asp-route-id="@ViewData["id"]" asp-action="Report" asp-controller="Report">Отчет</a>
        <div class="dropdown-divider"></div>
        <form asp-action="Delete" method="post">
            <input type="hidden" name="Id" value="@ViewData["id"]" />
            <input class="dropdown-item" type="submit" value="Удалить" />
        </form>
    </div>
</div>

TestTaskLibrary/Views/Books/List.cshtml
@model List<BookViewModel>
@{
    ViewData["Title"] = "List";
}
    <h3 class="mb-2">Управление книгами</h3>
<div class="mt-1 mb-1">
    <a class="btn btn-link" asp-action="Add">Добавить</a>
    <a class="btn btn-outline-success" asp-action="ReportAll" asp-controller="Report">Отчет</a>
</div>
@if (Model.Count != 0)
{
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Автор</th>
                    <th>Жанр</th>
                    <th>Статус</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var book in Model)
                {
                    <tr>
                        <td>
                            @book.Title
                        </td>
                        <td>
                            @book.Author
                        </td>
                        <td>
                            @book.Genre
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => book.CurrentStatus.Status)
                        </td>
                        <td>
                            <div class="btn-group">
                                @if (book.CurrentStatus.Status != Status.Issued)
                                {
                                    <a asp-action="Issue" asp-controller="Library" asp-route-id="@book.Id" class="btn btn-outline-primary">Выдать</a>
                                }
                                else
                                {
                                    <form class="input-group-prepend" asp-action="Take" asp-controller="Library" method="post">
                                        <input type="hidden" name="BookId" value="@book.Id" />
                                        <input class="btn btn-primary" type="submit" value="Вернуть" />
                                    </form>
                                }
                                <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-route-id="@book.Id" asp-action="Report" asp-controller="Report">Отчет</a>
                                    <div class="dropdown-divider"></div>
                                    <form asp-action="Delete" method="post">
                                        <input type="hidden" name="Id" value="@book.Id" />
                                        <input class="dropdown-item" type="submit" value="Удалить" />
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <p>Список пользователей пуст</p>
}

TestTaskLibrary/Views/Books/Lists.cshtml
@model List<BookViewModel>
@{
    ViewData["Title"] = "List";
}
    <h3 class="mb-2">Управление книгами</h3>
<div class="mt-1 mb-1">
    <a class="btn btn-link" asp-action="Add">Добавить</a>
    <a class="btn btn-outline-success" asp-action="ReportAll" asp-controller="Report">Отчет</a>
</div>
@if (Model.Count != 0)
{
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Автор</th>
                    <th>Жанр</th>
                    <th>Статус</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var book in Model)
                {
                    <tr>
                        <td>
                            @book.Title
                        </td>
                        <td>
                            @book.Author
                        </td>
                        <td>
                            @book.Genre
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => book.CurrentStatus.Status)
                        </td>
                        <td>
                            <div class="btn-group">
                                @if (book.CurrentStatus.Status != Status.Issued)
                                {
                                    <a asp-action="Issue" asp-controller="Library" asp-route-id="@book.Id" class="btn btn-outline-primary">Выдать</a>
                                }
                                else
                                {
                                    <form class="input-group-prepend" asp-action="Take" asp-controller="Library" method="post">
                                        <input type="hidden" name="BookId" value="@book.Id" />
                                        <input class="btn btn-primary" type="submit" value="Вернуть" />
                                    </form>
                                }
                                <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-route-id="@book.Id" asp-action="Report" asp-controller="Report">Отчет</a>
                                    <div class="dropdown-divider"></div>
                                    <form asp-action="Delete" method="post">
                                        <input type="hidden" name="Id" value="@book.Id" />
                                        <input class="dropdown-item" type="submit" value="Удалить" />
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <p>Список пользователей пуст</p>
}

TestTaskLibrary/Views/Books/TopListButtons.cshtml
<div class="mt-1 mb-1">
    <a class="btn btn-link" asp-action="Add">Добавить</a>
    <a class="btn btn-outline-success" asp-action="ReportAll" asp-controller="Report">Отчет</a>
</div>