TestTaskLibrary/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestTaskLibrary.Domain.Application.Interfaces.Repositories;
using TestTaskLibrary.Domain.Core;

namespace TestTaskLibrary.Controllers
{
    public class AuthorsController : GenericController<Author>
    {
        public AuthorsController(IGenericRepository<Author> repository) : base(repository)
        {
        }
    }
}

TestTaskLibrary/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.Commands;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.Queries;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.ViewModels;
using TestTaskLibrary.Domain.Application.Interfaces.Managers;
using TestTaskLibrary.Domain.Application.Interfaces.Repositories;
using TestTaskLibrary.Domain.Core;
using TestTaskLibrary.Infrastructure.Business;
using TestTaskLibrary.Infrastructure.Data;
using TestTaskLibrary.Models;
using TestTaskLibrary.Models.Books;

namespace TestTaskLibrary.Controllers
{
    [Authorize(Roles = RoleTypes.Librarian)]
    public class BooksController : GenericController<Book,BookViewModel>
    {

        public BooksController(IMediator mediator, IGenericRepository<Book> repository, IMapper mapper) : base(repository, mediator, mapper)
        {
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        //public async Task<IActionResult> List()
        //{
        //    var result = await mediator.Send(new GetBooksQuery());
        //    return View(result);
        //}

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> BookDatails(GetBookByIdQuery query)
        {
            var book = await mediator.Send(query);

            if (book != null)
            {
                return View(book);
            }

            return NotFound();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new AddBookViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                var command = mapper.Map<CreateBookCommand>(model);
                int id = await mediator.Send(command);
                return RedirectToAction("List");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteBookCommand command)
        {
            int id = await mediator.Send(command);
            return RedirectToAction("List");
        }
    }
}

TestTaskLibrary/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestTaskLibrary.Domain.Application.Features.GenreFeatures.Commands;
using TestTaskLibrary.Domain.Application.Features.GenreFeatures.ViewModels;
using TestTaskLibrary.Domain.Application.Interfaces.Repositories;
using TestTaskLibrary.Domain.Core;
using TestTaskLibrary.Models;
using TestTaskLibrary.Models.Genres;

namespace TestTaskLibrary.Controllers
{
    [Authorize(Roles = RoleTypes.Librarian)]
    public class GenresController : GenericController<Genre, GenreViewModel>
    {
        public GenresController(IGenericRepository<Genre> repository, IMapper mapper, IMediator mediator) : base(repository, mediator, mapper)
        {
        }

        [HttpPost]
        public async Task<IActionResult> Add(GenreAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                await mediator.Send(new CreateGenreCommand() { Name = model.Name });
                return RedirectToAction("List");
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var author = await repository.GetByIdAsync(id);
            if (author != null)
            {
                return View(new GenreEditViewModel() { Id = author.Id, Name = author.Name });
            }
            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(GenreEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                await mediator.Send(new EditGenreCommand() { Id = model.Id, Name = model.Name });
                return RedirectToAction("List");
            }
            return View(model);
        }
    }
}

TestTaskLibrary/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TestTaskLibrary.Domain.Application.Features.BookFeatures.ViewModels;
using TestTaskLibrary.Domain.Application.Interfaces.Repositories;
using TestTaskLibrary.Domain.Core;
using TestTaskLibrary.Models;
using TestTaskLibrary.Models.Users;

namespace TestTaskLibrary.Controllers
{
    [Authorize(Roles = RoleTypes.Admin)]
    public class UsersController : GenericController<User, UserViewModel>
    {
        private readonly UserManager<User> userManager;

        public UsersController(IGenericRepository<User> repository, IMediator mediator, IMapper mapper, UserManager<User> userManager) : base(repository, mediator, mapper)
        {
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        //public IActionResult List()
        //{
        //    return View(userManager.Users.Where(u => u.Email != "Admin").Select(u=>new UserViewModel() { UserName = u.Email, FullName = u.FullName, Id = u.Id}).ToList());
        //}

        [HttpGet]
        public IActionResult Add()
        {
            return View(new AddUserViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User() { Email = model.Email, UserName = model.Email, FullName = model.FullName };
                var result = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(user, model.Role.ToString());
                    return RedirectToAction("List");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> ChangePassword(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if(user != null)
            {
                return View(new ChangePasswordViewModel() { Id = user.Id});
            }
            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.Users.FirstOrDefaultAsync(u => u.Id == model.Id);
                if(user != null)
                {
                    var result = await userManager.RemovePasswordAsync(user);
                    if (result.Succeeded)
                    {
                        result = await userManager.AddPasswordAsync(user, model.Password);
                        if (result.Succeeded)
                        {
                            await userManager.UpdateAsync(user);
                            return RedirectToAction("List");
                        }
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("password", error.Description);
                            }
                        }
                    }
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                await userManager.DeleteAsync(user);
            }
            return RedirectToAction("List");
        }
    }
}

TestTaskLibrary/Views/Shared/ItemButtons.cshtml
    <div class="btn-group">
        <form class="mr-2" asp-action="Edit" method="get">
            <input type="hidden" name="Id" value="@ViewData["id"]" />
            <input class="btn btn-outline-primary" type="submit" value="Изменить" />
        </form>
        <form asp-action="Delete" method="post">
            <input type="hidden" name="Id" value="@ViewData["id"]" />
            <input class="btn btn-outline-danger" type="submit" value="Удалить" />
        </form>
    </div>

TestTaskLibrary/Views/Shared/List.cshtml
@model IEnumerable<object>

@{
    ViewData["Title"] = "List";
}
@{
    var t = Model.GetType();
    var gt = t.GenericTypeArguments[0];
    bool isBook = gt.Name == "BookViewModel";
    var props = gt.GetProperties();
    var idProp = props.FirstOrDefault(p => p.Name.ToLower() == "id");
    var statProp = props.FirstOrDefault(p => p.Name == "Status");
    var displayProps = props.Where(p => p.GetCustomAttributes(typeof(DisplayAttribute), false).Count() != 0);

    var header = displayProps.Select(p => new { Name = ((DisplayAttribute)(p.GetCustomAttributes(typeof(DisplayAttribute), false).FirstOrDefault())).Name ?? p.Name, ProperyName = p.Name, Propery = p });

    var sortProps = header.Select(i => new SelectListItem(i.Name, i.ProperyName, ViewData["SortField"]?.ToString() == i.ProperyName));

    var searhProps = header.Where(i => i.Propery.PropertyType == typeof(string)).Select(i => new SelectListItem(i.Name,i.ProperyName, ViewData["SearchField"]?.ToString() == i.ProperyName));
}


    @await Html.PartialAsync("TopListButtons")

    <form class="mt-3 mb-3" asp-action="List">
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Сортировать по</span>
                <select class="custom-select mr-3" name="sortField" asp-items="sortProps"></select>
                <select class="custom-select" name="searchField" asp-items="searhProps"></select>
            </div>
            <input class="form-control" type="text" value="@ViewData["Search"]" name="search" placeholder="Искать" />
            <div class="input-group-append">
                <input class="btn btn-outline-secondary" type="submit" value="Найти" />
            </div>
        </div>
    </form>

    <table class="table">
        <thead>
            <tr>
                @foreach (var h in header)
                {
                    <th>
                        @h.Name
                    </th>
                }
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var d in Model)
            {
                <tr>
                    @{ 
                        int i = 0;
                    }
                    @foreach (var p in displayProps)
                    {
                    <td>
                        @if (p.GetValue(d) is Enum)
                        {
                            var enumT = p.PropertyType;
                            var member = enumT.GetMember(@p.GetValue(d).ToString());
                            var atribs = member[0].GetCustomAttributes(typeof(DisplayAttribute), false);
                            if (atribs.Length <= 0)
                            {
                                @p.GetValue(d);
                            }
                            else
                            {
                                var da = (DisplayAttribute)atribs[0];
                                @da.Name;
                            }
                        }
                        else
                        {
                            if (isBook && i == 0)
                            {
                                <a asp-action="BookDatails" asp-controller="Books" asp-route-id="@idProp.GetValue(d)">@p.GetValue(d)</a>
                            }
                            else
                                @p.GetValue(d)

                            }
                    </td>
                        i++;
                    }
                    <td>
                        @{ 

                                ViewData["id"] = (int)idProp.GetValue(d);

                                if (statProp != null)
                                    ViewData["Status"] = (Status)statProp.GetValue(d);
                        }
                        @await Html.PartialAsync("ItemButtons", ViewData)
                    </td>
                </tr>
            }
        </tbody>
    </table>

@await Html.PartialAsync("Pagination",ViewData)

TestTaskLibrary/Views/Shared/Pagination.cshtml
<div class="row">
    <form class="col-3" action="List" method="get">
        <input type="hidden" name="search" value="@ViewData["Search"]" />
        <input type="hidden" name="searchField" value="@ViewData["SearchField"]" />
        <input value="@ViewData["SortField"]" name="sortField" type="hidden" />
        <div class="input-group">
            <input class="form-control mr-1" type="number" name="PageIndex" value="@ViewData["PageIndex"]" />
            <input class="btn btn-outline-primary" type="submit" value="Перейти" />
        </div>
    </form>
</div>

TestTaskLibrary/Views/Shared/TopListButtons.cshtml
@{
    Layout = null;
}

    <div class="mt-1 mb-1">
        <a class="btn btn-link" asp-action="Add">Добавить</a>
    </div>

TestTaskLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand mr-auto" asp-action="Index" asp-controller="Library">На главную</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <a class="nav-link" asp-action="List" asp-controller="Users">Управление пользователями</a>
                            }
                            if (User.IsInRole("Librarian"))
                            {
                                <a class="nav-link" asp-action="List" asp-controller="Authors">Авторы</a>
                                <a class="nav-link" asp-action="List" asp-controller="Genres">Жанры</a>
                            }

                            <form class="form-inline" method="post" asp-action="LogOut" asp-controller="Account">
                                <input class="btn btn-outline-danger" type="submit" value="Выход" />
                            </form>
                        }
                        else
                        {
                            <a class="nav-link" asp-action="LogIn" asp-controller="Account">Вход</a>
                        }
                    </div>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>